"""added is_active attribute to the User model

Revision ID: 712f11d90611
Revises: 
Create Date: 2023-07-07 14:48:40.616454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712f11d90611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('urls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url_source', sa.VARCHAR(length=1200), nullable=False),
    sa.Column('scissored_url', sa.VARCHAR(length=10), nullable=False),
    sa.Column('clicks', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scissored_url')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('passwordHash', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
